In [3]:
import numpy as np

Valid sudoku

In [4]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]   
    
    
])

For rows

In [5]:
b=np.sum(s,axis = 1)  # col axis =0  row axis = 1  ( valid sudoku - every row sum = 45)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [7]:
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for rows it is valid")
    

for rows it is valid


For Columns

In [16]:
c=np.sum(s,axis = 0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [17]:
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

Check every 3x3 block sum is 45

In [18]:
# we will use slicing
s[0:3,0:3]

In [8]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [9]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [10]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [12]:
for i in range(0,9,3):
    for j in range(0,9,3):
         n= s[i:i+3,j:j+3]
         print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
# hence this is a valid sudoku

In [27]:
# Columns : [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78], #student 1
    [19,92,88], #student 2
    [17,76,95], #student 3
    [18,65,85], #student 4
    [20,90,85] #student 5
])

In [28]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [29]:
# Find the average age of students

np.mean(data[:,0])

np.float64(18.4)

In [30]:
# Extract maths marks of each student
data[:,1]

array([85, 92, 76, 65, 90])

In [31]:
# Find highest science marks
np.max(data[:,2])

np.int64(95)

In [23]:
# Get details of the student who scored more than 90 in maths 
data[data[:,1] > 90]

array([[19, 92, 88]])

In [33]:
# Increse Math marks of all student by 5 
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 85],
       [20, 95, 85]])

In [38]:
# Find how many students are younger than 90
len(data[data[:,0]<19])

3

In [42]:
# Calculate the average marks in each subjext (column-wise  mean)

np.mean(data[:,1:], axis=0)

array([86.6, 86.2])

In [43]:
# Get data of students who scored at least 80 in both subjects.

data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [46]:
# Replace all Science marks < 75 with 0.

data[:,2][data[:,2]<80]=0
data

array([[18, 90,  0],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 85],
       [20, 95, 85]])