In [4]:
import numpy as np

Valid sudoku

In [6]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]   
    
    
])

For rows

In [10]:
b=np.sum(s,axis = 1)  # col axis =0  row axis = 1  ( valid sudoku - every row sum = 45)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [11]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [12]:
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for rows it is valid")
    

for rows it is valid


For Columns

In [16]:
c=np.sum(s,axis = 0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [17]:
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

Check every 3x3 block sum is 45

In [18]:
# we will use slicing
s[0:3,0:3]

In [ ]:
# Columns : [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78], #student 1
    [19,92,88], #student 2
    [17,76,95], #student 3
    [18,65,85], #student 4
    [20,90,85] #student 5
])