In [1]:
import numpy as np

In [35]:
# arrayy operations

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
list = [1,2, 3 , "thing"]

In [6]:
a = np.array(list)
a

array(['1', '2', '3', 'thing'], dtype='<U21')

In [7]:
l = [[1,2],[2,4], [5,9]]
l

[[1, 2], [2, 4], [5, 9]]

In [8]:
np.array(l)

array([[1, 2],
       [2, 4],
       [5, 9]])

In [10]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
a1 = np.arange(1,11,2)
a1

array([1, 3, 5, 7, 9])

In [13]:
a2 = np.linspace(1,5,5)
a2

array([1., 2., 3., 4., 5.])

In [14]:
np.random.rand(5)

array([0.9949347 , 0.71590325, 0.55318042, 0.71913093, 0.96305951])

In [15]:
np.random.randn(10)

array([-0.98509645, -0.47651212,  1.61661785, -1.60212616,  0.48598148,
        1.83758471,  0.18796062, -0.2123634 , -2.03840518,  0.26836199])

In [20]:
np.random.randint(10,20,2)

array([10, 14], dtype=int32)

In [22]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
a1 = np.array([1,3,4,6])

In [27]:
a2 = np.array([2,6,3,2])

In [29]:
a1+a2

array([3, 9, 7, 8])

In [30]:
a1-a2

array([-1, -3,  1,  4])

In [31]:
a1*a2

array([ 2, 18, 12, 12])

In [32]:
a1/a2

array([0.5       , 0.5       , 1.33333333, 3.        ])

In [33]:
a1//a2

array([0, 0, 1, 3])

In [36]:
# Broadcasting


In [37]:
l = [10,20,30,40]
arr = np.array(l)

In [38]:
arr+10

array([20, 30, 40, 50])

In [42]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
arr2 = arr2+2
arr2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [43]:
# deep and Shallow copy

In [44]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [49]:
slice = slice*10
slice

array([100, 200, 300, 400, 500])

In [50]:
a # a will not change by changing its any slice because it store as a different copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a[4:6] *10

array([50, 60])

In [52]:
a # no change

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
b=a

In [54]:
b[0] =99

In [55]:
b # b will change

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
a
# a array will also chnaged (it means we are creating a deep copy when we change b then a will also change)

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
# if we don't want to change we have to create a sallow copy by using (.copy())

In [58]:
b= a.copy()

In [60]:
b[0]=20
b

array([20,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [63]:
# hence b changed but a remain as it is.
# (.copy() will create a copy of a at different location but previously the location of both a nad b was same)

In [64]:
# Matrix Operation

In [65]:
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[2,4], [6,0]])

In [67]:
 # matrix multiplication

In [68]:
mat1 @ mat2

array([[14,  4],
       [30, 12]])

In [69]:
np.dot(mat1,mat2)

array([[14,  4],
       [30, 12]])

In [70]:
# Transpose of matrix

In [72]:
mat1.T

array([[1, 3],
       [2, 4]])

In [73]:
# Advance Array Manipulation

In [74]:
# Stacking Array

In [75]:
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])

In [76]:
 # There are three types of stack
 #    (i) Simple Stack
 #    (ii) Vertical Stack
 #    (iii) Horizontal Stack

In [77]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
 # vertical stack -  .vstack((a,b))  (stack array row wise) 

In [79]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
# horizontal stack -  .hstack((a,b))  (stack array column wise)

In [81]:
# column stack 
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [82]:
# splitting array

In [83]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
# horizontal split

In [85]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [86]:
# vertical split

In [87]:
np.vsplit(c,2) # split into 2 parts

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [88]:
a = np.vsplit(c,4) # split into 4 parts

In [89]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
