In [1]:
import numpy as np

In [35]:
# arrayy operations

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
list = [1,2, 3 , "thing"]

In [6]:
a = np.array(list)
a

array(['1', '2', '3', 'thing'], dtype='<U21')

In [7]:
l = [[1,2],[2,4], [5,9]]
l

[[1, 2], [2, 4], [5, 9]]

In [8]:
np.array(l)

array([[1, 2],
       [2, 4],
       [5, 9]])

In [10]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
a1 = np.arange(1,11,2)
a1

array([1, 3, 5, 7, 9])

In [13]:
a2 = np.linspace(1,5,5)
a2

array([1., 2., 3., 4., 5.])

In [14]:
np.random.rand(5)

array([0.9949347 , 0.71590325, 0.55318042, 0.71913093, 0.96305951])

In [15]:
np.random.randn(10)

array([-0.98509645, -0.47651212,  1.61661785, -1.60212616,  0.48598148,
        1.83758471,  0.18796062, -0.2123634 , -2.03840518,  0.26836199])

In [20]:
np.random.randint(10,20,2)

array([10, 14], dtype=int32)

In [22]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
a1 = np.array([1,3,4,6])

In [27]:
a2 = np.array([2,6,3,2])

In [29]:
a1+a2

array([3, 9, 7, 8])

In [30]:
a1-a2

array([-1, -3,  1,  4])

In [31]:
a1*a2

array([ 2, 18, 12, 12])

In [32]:
a1/a2

array([0.5       , 0.5       , 1.33333333, 3.        ])

In [33]:
a1//a2

array([0, 0, 1, 3])

In [ ]:
# Broadcasting